; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{507D39E7-2FC6-42FC-92A4-DBFE1F249CA2}
AppName=STalker
AppVersion=0.5.0.0
;AppVerName=STalker 0.5.0.0
AppPublisher=Heavy Opposition Systems
DefaultDirName={pf}\STalker
DisableProgramGroupPage=yes
LicenseFile=C:\Users\Antillian\source\repos\STalker\STalker\LICENSE.txt
OutputDir=C:\Users\Antillian\source\repos\STalker\STalker\inno
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "C:\Users\Antillian\source\repos\STalker\STalker\bin\Release\stalker.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Antillian\source\repos\STalker\STalker\README.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Antillian\source\repos\STalker\STalker\CHANGELOG.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Antillian\source\repos\STalker\STalker\LICENSE.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\STalker"; Filename: "{app}\stalker.exe"
Name: "{commondesktop}\STalker"; Filename: "{app}\stalker.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\STalker"; Filename: "{app}\stalker.exe"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\stalker.exe"; Description: "{cm:LaunchProgram,STalker}"; Flags: nowait postinstall skipifsilent

